### ISSUE TITLE
Integrate with the powerful router and dispatcher github.com/gorilla/mux

### ISSUE THREAD

**Issue by duanbing** [opentracing-contrib/go-stdlib#23]
`github.com/gorilla/mux` is a powerful URL router and dispatcher for golang and heavily used.  So I have a proposal that we can integrate mux with go-stdlib.
   But we know gorilla/mux manages a private context,named github.com/gorilla/context  for itself to store additional data, such variables from `Paths can have variables`
   So we also should forward the context.

**Comment by duanbing** [comment]
refer to https://github.com/opentracing-contrib/go-stdlib/issues/23

**Comment by yurishkuro** [comment]
Sorry, but how it's this an issue for go-stdlib repo?

**Comment by yurishkuro** [comment]
we can create a separate repo opentracing-contrib/go-gorilla, if you are interested in maintaining it. But I'd be interested to see if gorilla-specific logic could be built on top of server instrumentation already present in this repo, e.g. by providing gorilla-specific extractor function to get the span name from the route.

**Comment by duanbing** [comment]
I see. Building on this server instrumentation is also what I think about,  I'll check if there is similar repo in gorilla, cause gorilla supports custom defined middleware, we can build a middleware who injects the tracer.

**Comment by duanbing** [comment]
I made this issue, cause it's easy to support gorilla, but maybe not so much graceful for this repo.

**Comment by duanbing** [comment]
and the Usage looks like this : https://github.com/duanbing/goabc/blob/master/tracing/mux.go

**Comment by yurishkuro** [comment]
Looks good. I'd certainly recommend putting it into opentracing-contrib. Let me know if you'd like me to create a new repo, and we can iterate on the actual impl (e.g. I see some places I'd prefer to change from your example). 

PS we're using Gorilla in Jaeger, with a custom wrapper to add tracing, so I'd be interested in switching to this new module.

**Comment by duanbing** [comment]
Yes, It's ok to create a new repo for this and improve it together.
