### ISSUE TITLE
Make injecting tracing context optional

### ISSUE THREAD

**Issue by nvx** [opentracing-contrib/go-stdlib#43]
When connecting to external services sending the tracing context in HTTP headers provides no value and should be able to be suppressed. The client side tracing is still however useful, so it is not desirable to simply not trace the request at all.

**Comment by yurishkuro** [comment]
> When connecting to external services sending the tracing context ... provides no value

some people would disagree: https://w3c.github.io/trace-context/

**Comment by nvx** [comment]
I'm not sure what part of the linked page you're referring to specifically, but I did notice this in it:

6.1 Information exposure
As mentioned in the privacy section, information in traceparent and tracestate headers may carry information that can be considered sensitive. For example, traceparent may allow one call to be correlated to the data sent with another call. tracestate may imply the version of monitoring software used by the caller. This information could potentially be used to create a larger attack.

Application owners should either ensure that no proprietary or confidential information is stored in the tracestate, or they should ensure that tracestate isn't present in requests to external systems.


Which seems to agree that providing a way to omit the the fields to external systems.

**Comment by yurishkuro** [comment]
The passage you quoted says "don't pass sensitive info", not that you should not pass trace context further. That whole initiative is to develop a standard for different tracing systems to interact.

But anyway, I agree that in some cases you may want to suppress outbound trace context while  still creating client spans. Feel free to put up a PR to support that, e.g. an option `InjectSpanContext(false)`
